### ISSUE TITLE
Add @saschaeggi as a Co-Maintainer

### ISSUE THREAD

**Issue by saschaeggi** [backdrop-contrib/gin#26]
If Tonic should keep more or less it's roots tied to Gin you could add me as a Co-Maintainer so I can contribute changes/fixes made upstream in Gin.

**Comment by laryn** [comment]
@saschaeggi That would be awesome! You are of course welcome as a co-maintainer. I'm checking what needs to happen from the `backdrop-contrib` side and will post back here.

**Comment by laryn** [comment]
@saschaeggi I've added you in the README as a maintainer. In order to grant you access within the `backdrop-contrib` group, you just need to indicate agreement with the `Backdrop Contributed Project Agreement` as shown on this page:

 - https://docs.backdropcms.org/documentation/contrib-application-process

**Comment by saschaeggi** [comment]
@laryn https://github.com/backdrop-ops/contrib/issues/718

**Comment by klonos** [comment]
@saschaeggi I've approved your request and have sent an invite through to add you to the Backdrop contrib authors group. Welcome! ...really glad to have you onboard ...I love your work on Gin ❤️

**Comment by laryn** [comment]
Great! @saschaeggi Let me know if you are all squared away.

**Comment by saschaeggi** [comment]
@klonos @laryn it worked like a charm, thanks 😊
