### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by saschaeggi** [backdrop-contrib/gin#27]
You're more than welcome to keep the name «Gin» if you like.

**Comment by laryn** [comment]
@saschaeggi Thanks! Initially I wasn't sure how closely it would stick to Gin visually so I didn't want to step on any toes or cause any confusion and thought it might be better to rename it, change icons, etc. for a slight distinction -- but I think it's ending up quite similar visually. Since you don't mind and especially given https://github.com/backdrop-contrib/tonic/issues/26 perhaps it does make sense to just keep it as Gin.

**Comment by laryn** [comment]
@saschaeggi Given this suggestion and [trying to stick close to the original Gin code](https://github.com/backdrop-contrib/tonic/issues/29) where possible I'm going to backup to the point before I changed the name in the commit history and then re-apply or re-work the changes to get to the current point. This might slow things down a bit (especially since I'm going on vacation shortly) but should be a better base to start from going forward.

**Comment by laryn** [comment]
I've moved the Tonic branch to `1.x-3.x-tonic` and started a new `1.x-3.x` branch for Gin. It's not quite as far along as Tonic was but will be a better base to build on going forward in an attempt to make relevant upstream changes simpler.
